# Generated by Django 5.1.6 on 2025-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_list_items_created_at_alter_list_items_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_items',
            name='status',
            field=models.CharField(choices=[('not_watched', 'Не смотрю'), ('will_watch', 'Буду смотреть'), ('watching', 'Смотрю'), ('dropped', 'Заброшен')], default='not_watched', max_length=20),
        ),
    ]
