# Generated by Django 5.1.6 on 2025-02-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_list_items_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_items',
            name='status',
            field=models.CharField(choices=[('not_watched', 'Не смотрю'), ('will_watch', 'Буду смотреть'), ('watching', 'Смотрю'), ('dropped', 'Заброшен'), ('watched', 'Просмотрено')], default='not_watched', max_length=20),
        ),
    ]
